version: "3.9"

services:
  ketch-event-forwarder:
    build:
      context: .
      dockerfile: docker/java-ketch-forwarder/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      KETCH_USER_NAME: username1
      KETCH_USER_PASSWORD: password1

networks:
  default:
    name: ketch_event_forwarder_default
